# Generated by Django 5.1.2 on 2024-10-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(max_length=100)),
                ('Business_Hours', models.CharField(max_length=100)),
                ('Business_type', models.CharField(max_length=100)),
                ('Business_Location', models.CharField(max_length=200)),
                ('services', models.TextField()),
                ('About_business', models.TextField()),
            ],
        ),
    ]
