# Generated by Django 5.1.2 on 2024-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0004_chatbotinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
