# Generated by Django 5.1.2 on 2024-10-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0007_flowquestion_flowconversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowquestion',
            name='chatbot',
        ),
        migrations.DeleteModel(
            name='FlowConversation',
        ),
        migrations.DeleteModel(
            name='FlowQuestion',
        ),
    ]
