# Generated by Django 5.1.2 on 2024-10-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0009_question_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='ChatBotApp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(),
        ),
    ]
