# Generated by Django 5.1.2 on 2024-10-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0010_alter_option_next_question_alter_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('option', 'Option Based')], default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='chatbot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ChatBotApp.chatbot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question_set', to='ChatBotApp.question'),
        ),
    ]
