# Generated by Django 5.1.2 on 2024-10-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0011_question_answer_type_question_chatbot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chatbot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ChatBotApp.chatbot'),
        ),
    ]
