# Generated by Django 5.1.2 on 2024-10-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0012_alter_question_chatbot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.AlterField(
            model_name='option',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_question', to='ChatBotApp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chatbot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ChatBotApp.chatbot'),
        ),
    ]
