# Generated by Django 5.1.2 on 2024-10-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0013_remove_question_answer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chatbot',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
