# Generated by Django 5.1.2 on 2024-11-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0017_alter_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
